server:
  port: 8088

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://rm-0jlty78wspyjbg764co.rwlb.rds.aliyuncs.com:3306/user_info?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root_user
    password: Staffcloud&2024
    driver-class-name: com.mysql.cj.jdbc.Driver

data-dir: /app/data
